spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_swipe?useUnicode=true&characterEncoding=utf8&useSSL=TRUE&createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8080
  
qiniuyun:
  domain: s35106op1.hn-bkt.clouddn.com
  bucket: web-swipe
  access-key: Zmp5QecX_NwwnBFKOAfOjmFVb15CIR2x4-jedmuQ
  secret-key: HnuNUH9lumfXoFxXcrrelbucVkTXG5Hg00VxL9Sn